# route javaScript pour l'administration
apa_admin_getLastChapterNumber:
    path:     /admin/getLastChapterNumber
    defaults: { _controller: ApaAdminBundle:Admin:getLastChapterNumber }
    options:
        expose: true