imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'

# Gestion de l'internationalisation
sonata_intl:
    timezone:
        locales:
            fr: Europe/Paris

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    java: C:\Program Files (x86)\Java\jre1.8.0_65\bin\java.exe
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        # Attention! la version 2.4.8 sous mon windows ne marchait pas 
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar 
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
        #    json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true

# Swiftmailer
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
# LiipImagineBundle (redimensionnement d'image)
liip_imagine:
  filter_sets:
    miniatureAvatar2:
        quality: 75
        filters:
           thumbnail: { size: [90, 90], mode: outbound }
    normalAvatar:
        quality: 75
        filters:
           thumbnail: { size: [150, 150], mode: outbound }
    my_heighten:
            filters:
                relative_resize: { heighten: 150 }

# KnpPaginatorBundle (pagination)
knp_paginator:
    # Nombre de liens en bas de la pagination
    page_range: 1
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

# FOSUser (utilisateur)  
# Type de bdd. Nom du firewall des utilisateurs. Classe de l'entité user
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Apa\UserBundle\Entity\User
    
# SonataAdminBundle (administration)
    # Généralités (attention l'indentation est interprétée)
sonata_block:
    default_contexts: [cms]
    blocks:
        # SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
# Services appelés pour l'administration
imports:
    - { resource: @ApaAdminBundle/Resources/config/admin.yml }
# Titre et logo de l'administration
sonata_admin:
    title:      Administration
    title_logo: img/logo-oetherium.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::layout.html.twig