apa_generalPage:
    resource: "@ApaGeneralPageBundle/Resources/config/routing.yml"
    prefix:   /

apa_user:
    resource: "@ApaUserBundle/Resources/config/routing.yml"
    prefix:   /

apa_story:
    resource: "@ApaStoryBundle/Resources/config/routing.yml"
    prefix:   /
    
apa_admin:
    resource: "@ApaAdminBundle/Resources/config/routing.yml"
    prefix:   /

# redimensionnement d'image
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#routes pour le bundle fos user
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
# administration
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
