<?php

namespace Apa\StoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnexTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnexTextRepository extends EntityRepository
{
    public function getIdByOrder($order)
    {    
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a.id')
           ->from('ApaStoryBundle:AnnexText', 'a')
           ->orderBy('a.id', $order);
           
        return $qb->getQuery()
                ->setMaxResults(1)
                ->getResult();
    }
}
