<?php

namespace Apa\StoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnexTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnexTextRepository extends EntityRepository
{
    public function getNextId($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a.id')
            ->from('ApaStoryBundle:AnnexText', 'a')
            ->where("a.id > $id")
            ->orderBy('a.id', 'ASC');

        return $qb->getQuery()
                ->setMaxResults(1)
                ->getOneOrNullResult();
    }

    public function getPreviousId($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a.id')
            ->from('ApaStoryBundle:AnnexText', 'a')
            ->where("a.id < $id")
            ->orderBy('a.id', 'DESC');

        return $qb->getQuery()
                ->setMaxResults(1)
                ->getOneOrNullResult();
    }
}
