<?php

namespace Apa\StoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterStoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterStoryRepository extends EntityRepository
{
    public function getMainCharacters()
    {    
        $qb = $this->createQueryBuilder('c')
              ->where('c.main = 1');

        return $qb->getQuery()
                  ->getResult();
    }
}
