<?php

namespace Apa\StoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageBookRepository extends EntityRepository
{
}
