<?php

namespace Proxies\__CG__\Apa\StoryBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CharacterStory extends \Apa\StoryBundle\Entity\CharacterStory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'images', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'id', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'name', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'firstname', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'arrayFirstnames', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'species', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'gender', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'dateBirth', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'placeBirth', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'citation', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'description', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'avatar', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'file', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'oldAvatar', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'main');
        }

        return array('__isInitialized__', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'images', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'id', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'name', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'firstname', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'arrayFirstnames', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'species', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'gender', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'dateBirth', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'placeBirth', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'citation', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'description', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'avatar', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'file', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'oldAvatar', '' . "\0" . 'Apa\\StoryBundle\\Entity\\CharacterStory' . "\0" . 'main');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CharacterStory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setArrayFirstnames($arrayFirstnames)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArrayFirstnames', array($arrayFirstnames));

        return parent::setArrayFirstnames($arrayFirstnames);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayFirstnames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayFirstnames', array());

        return parent::getArrayFirstnames();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecies($species)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecies', array($species));

        return parent::setSpecies($species);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecies', array());

        return parent::getSpecies();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateBirth($dateBirth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateBirth', array($dateBirth));

        return parent::setDateBirth($dateBirth);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateBirth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateBirth', array());

        return parent::getDateBirth();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceBirth($placeBirth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceBirth', array($placeBirth));

        return parent::setPlaceBirth($placeBirth);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceBirth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceBirth', array());

        return parent::getPlaceBirth();
    }

    /**
     * {@inheritDoc}
     */
    public function setCitation($citation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCitation', array($citation));

        return parent::setCitation($citation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCitation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCitation', array());

        return parent::getCitation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar($avatar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', array($avatar));

        return parent::setAvatar($avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', array());

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', array($file));

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', array());

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setMain($main)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMain', array($main));

        return parent::setMain($main);
    }

    /**
     * {@inheritDoc}
     */
    public function getMain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMain', array());

        return parent::getMain();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\Apa\StoryBundle\Entity\Image $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', array($images));

        return parent::addImage($images);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\Apa\StoryBundle\Entity\Image $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', array($images));

        return parent::removeImage($images);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setImages($images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImages', array($images));

        return parent::setImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function lifecycleFileUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'lifecycleFileUpload', array());

        return parent::lifecycleFileUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', array());

        return parent::getUploadDir();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array());

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePathOldAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePathOldAvatar', array());

        return parent::getAbsolutePathOldAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

}
